### PR TITLE
Re-add cpp file

### PR DESCRIPTION
**Pull request by jakirkham**
Seems I was incorrect by proposing PR ( https://github.com/TuragaLab/zwatershed/pull/2 ). This reverts that change. With this, it appears to build and import correctly for me. It is probably worth merging this and cutting a fresh release. Then we should update PR ( https://github.com/conda-forge/staged-recipes/pull/917 ) with the new version.

### CODE REVIEW

**Comment by jakirkham** [comment]
Did this ever get a new PyPI release?

**Comment by csinva** [comment]
Not yet, I am adding one method and then will rerelease sometime next week.

**Comment by jakirkham** [comment]
Ok, sounds good.

**Comment by grisaitis** [comment]
@csinva does this merge fix a bug? if so i think it would make sense to ship it now, e.g. as `0.7.1`.

**Comment by jakirkham** [comment]
It makes sure it builds. Though it doesn't affect existing working builds. I'll let you guys determine the priority of it.

**Comment by csinva** [comment]
yeah @grisaitis the code you have works, this just makes it easier to install.

**Comment by grisaitis** [comment]
ok. y'all know more than i do about what issue this solves. i just successfully pip-installed malis and imported it, no problem.

**Comment by jakirkham** [comment]
So, if you are wanting to pip install this in the near term, I would argue it is worth a patch release. If not, it can be bundled with whatever later changes are worth a release. In any event, making a new release on PyPI is extremely easy.

**Pull request merged**
