### PR TITLE
Fix some compilation issues (add includes, libs, clean flags)

### PR DESCRIPTION
**Pull request by jakirkham**
So, this almost fixes it. This will build all the way through. There still seems to be a directory issue which need to be resolved. Basically the compiled Cython code is not landing in the module like it should. Unfortunately, I don't think I have time to resolve this so I'm going to hand it back to you at this point.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @Chandan

**Comment by csinva** [comment]
alright thanks, I’ll look into it.

- Chandan

**Comment by jakirkham** [comment]
Ok, I fixed the install location, but there is a missing symbol at import time. 😞

**Comment by jakirkham** [comment]
I'm guessing this need something like the Boost libraries to link against. Not sure what those are. That should be an easy fix though.

**Pull request merged**
